spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/order?serverTimezone=Asia/Kolkata
    username: rishabh
    password: rishabh
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Kolkata

#  h2:
#    console:
#      enabled: true
#  datasource:
#    url: jdbc:h2:mem:test
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: create

server:
    port: 8083
