spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/product
#    url: jdbc:mysql://localhost:3307/rishabh
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Kolkata

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: "*"

app:
  message: "Hello Product!"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true